name: soul

on:
  push:
  pull_request:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1]
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Prepare and Run Soul Script ðŸš€
        timeout-minutes: 240 
        run: |
          echo "Starting job ${{ matrix.job }}"
          pip3 install python-telegram-bot aiohttp asyncio
          python3 SOULCRACK.py
          echo "Job ${{ matrix.job }} finished"
